spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #连接池配置
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 60000
    #配置隔多久进行一次检测(检测可以关闭的空闲连接)
    time-between-eviction-runs-millis: 60000
    #配置连接在池中的最小生存时间
    min-evictable-idle-time-millis: 300000
    validation-query: select 1 from DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  mvc:
    #当出现 404 错误时, 直接抛出异常
    throw-exception-if-no-handler-found: true

  resources:
    #不要为我们工程中的资源文件建立映射
    add-mappings: false
logging:
  level:
    com.cc.springbootmodel.dao:
      DEBUG
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params:
    count:
      countSql
  page-size-zero: true
mapper:
  mappers: com.cc.springbootmodel.core.universal.Mapper
server:
  port: 8090